version: '3'
services:
  flask-media-server:
    container_name: flask_media_server
    build:
      context: .
      args:
        - FLASK_ENV=${FLASK_ENV:-development}
    ports:
      - "8081:8081"
    volumes:
      - ${VIDEO_MOUNT:-/mnt/data/videos}:/app/videos
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
    command: python3 app.py
    restart: unless-stopped