version: '3'
services:
  flask-media-server:
    container_name: flask_media_server
    build: .
    ports:
      - "8081:8081"
    volumes:
      - /mnt/data/videos:/app/videos
    environment:
      - FLASK_ENV=development
    command: python3 app.py
    restart: unless-stopped
